---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: hybrid-cloud-demo

# Adds hybrid-cloud-demo label to all resources.
commonLabels:
  app: hybrid-cloud-frontend

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service.yaml
  - route.yaml
